variable "web_instance_count" {}
variable "web_ami" {}
variable "web_instance_type" {}
variable "private_subnet_id" {}
variable "public_subnet_id" {}
variable "vpc_cidr_block" {}
variable "key_name" {}
variable "environment" {}
variable "vpc_id" {}